services:
  - type: web
    name: shc-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build:api
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shc-db
          property: connectionString
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: SHIPENGINE_KEY
        sync: false
      - key: PHONECHECK_USERNAME
        sync: false
      - key: PHONECHECK_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://buyback-a0f05.web.app,https://secondhandcell.com
      - key: APP_FRONTEND_URL
        value: https://buyback-a0f05.web.app
      - key: PORT
        value: 5000
